#Question 1

In [27]:
import cvxpy as cp
import numpy as np

# Define known quantity
D = np.array([3475, 1223, 2260, 2700, 2950])
M = np.array([0, 0.47 , 0.5, 0.4, 0.3])
S = np.array([2000, 1600, 1000, 990, 2800])
T = np.array([0.85, 0.9, 0.85, 0.85, 0.9]) 
I = np.ones(5)
ZERO = np.zeros((5,5))
Prod = np.array([[1,1,0,0,0],
                [1,1,1,1,0],
                [0,1,1,1,1],
                [0,1,1,0,1],
                [0,0,0,0,1]]
                )
#Define Variable
F = cp.Variable(5, nonneg=True)
R = cp.Variable((5,5), nonneg=True)

#Define Constraint
constraints = [ 
    cp.multiply(M, D) <= F,
    D <= cp.multiply((I.T@R).T ,T) + F, 
    R@I <= S,
    cp.multiply(R,(np.ones((5,5))-Prod)).sum() == 0
    ]

In [28]:

#Define Objective
objective = cp.Minimize(F.T@I)
prob = cp.Problem(objective, constraints)
prob.solve(solver=cp.MOSEK, verbose=True)

                                     CVXPY                                     
                                     v1.4.1                                    
(CVXPY) Oct 15 09:36:20 PM: Your problem has 30 variables, 4 constraints, and 0 parameters.
(CVXPY) Oct 15 09:36:20 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Oct 15 09:36:20 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Oct 15 09:36:20 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Oct 15 09:36:20 PM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Oct 15 09:36:20 PM: Compiling problem (target solver=MOSEK).
(CV

5755.489444444713

Result

In [29]:
print("F: ", F.value)
print("R: " ,R.value)

F:  [1325.86990549  574.81000001 1302.8330352  1666.97650376  885.        ]
R:  [[1827.46715478  172.53284522    0.            0.            0.        ]
 [ 700.92119171   96.24630445  218.24180288  584.59070095    0.        ]
 [   0.          128.98739744  240.28154322  630.73105933    0.        ]
 [   0.          322.44456399  667.55543601    0.            0.        ]
 [   0.            0.            0.            0.         2800.        ]]


Varification

In [37]:
print(np.multiply(M, D))
print("Production:" , np.multiply((I.T@R.value).T ,T) + F.value)
print("Used Recycle from each type of paper",R.value@I)

[   0.    574.81 1130.   1080.    885.  ]
Production: [3475. 1223. 2260. 2700. 3405.]
Used Recycle from each type of paper [2000. 1600. 1000.  990. 2800.]


#Question 2

In [1]:
import cvxpy as cp
import numpy as np

A = np.array(
    [[-1,0.4,0.8],
     [1,0,0],
     [0,1,0]
     ]
)
b = np.array([1,0,0.5])
x_des = np.array([7,2,-6])
I = np.ones(10)


In [4]:
#Define Variable
X = cp.Variable((11,3))
U = cp.Variable(10)
epi = cp.Variable(10)
#Define Constraint
constraints = [ 
    X[i + 1] == A @ X[i] + b*U[i] for i in range(10) 
    ]
print(constraints)
constraints.append(X[0] == np.array([0,0,0]))
constraints.append(X[10] == x_des)
constraints.extend([cp.abs(U[i])<= epi[i] for i in range(10)] )
constraints.extend([cp.power(U[i],2)<= epi[i] for i in range(10)] )
##why u[i]*u[i] not ok

#Define Objective
objective = cp.Minimize(epi.T@I)
prob = cp.Problem(objective, constraints)
prob.solve(solver=cp.MOSEK, verbose=True)

[Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,))), Equality(Expression(AFFINE, UNKNOWN, (3,)), Expression(AFFINE, UNKNOWN, (3,)))]
                                     CVXPY                                     
                                     v1.4.1                                    
(CVXPY) Oct 15 11:22:39 PM: Your proble

(CVXPY) Oct 15 11:22:39 PM: Finished problem compilation (took 3.811e-02 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Oct 15 11:22:39 PM: Invoking solver MOSEK  to obtain a solution.


(CVXPY) Oct 15 11:22:39 PM: Problem
(CVXPY) Oct 15 11:22:39 PM:   Name                   :                 
(CVXPY) Oct 15 11:22:39 PM:   Objective sense        : maximize        
(CVXPY) Oct 15 11:22:39 PM:   Type                   : CONIC (conic optimization problem)
(CVXPY) Oct 15 11:22:39 PM:   Constraints            : 73              
(CVXPY) Oct 15 11:22:39 PM:   Affine conic cons.     : 0               
(CVXPY) Oct 15 11:22:39 PM:   Disjunctive cons.      : 0               
(CVXPY) Oct 15 11:22:39 PM:   Cones                  : 10              
(CVXPY) Oct 15 11:22:39 PM:   Scalar variabl

70.48736541182342

In [6]:
print("X", X.value)
print("U", U.value)

X [[-0.00000000e+00 -0.00000000e+00 -0.00000000e+00]
 [-1.09662933e+00  2.71963610e-07 -5.48314667e-01]
 [-3.42022266e-01 -1.09662933e+00 -4.99999716e-01]
 [ 2.17665468e+00 -3.42022266e-01  2.40012628e-01]
 [-5.78685220e+00  2.17665468e+00 -2.17472161e+00]
 [ 9.13413263e+00 -5.78685220e+00  4.28485260e+00]
 [-1.13693599e+01  9.13413263e+00 -7.46103646e+00]
 [ 1.14171111e+01 -1.13693599e+01  1.03155963e+01]
 [-7.71237810e+00  1.14171111e+01 -1.13693600e+01]
 [ 2.00000000e+00 -7.71237810e+00  1.08252438e+01]
 [ 7.00000000e+00  2.00000000e+00 -6.00000000e+00]]
U [-1.09662933e+00 -9.99999975e-01  2.67328392e+00 -3.66539870e+00
  4.21639583e+00 -3.34836851e+00  2.36292724e+00 -5.07369110e-08
 -1.18373455e+00  3.42475620e+00]


#Question 3

In [11]:
import cvxpy as cp
import numpy as np

v1 = 1
v2 = v1/1.5
v3 = v1/1.3
V = np.array([v1, v2, v3])
H = np.array([1, 1, 0.5])
X = cp.Variable(3,nonneg = True)
L = cp.Variable(3,nonneg = True)
T = cp.Variable(1)
#Define Constraint
constraints = [ 
    cp.multiply(L,cp.power(V,-1)) <= T,
    cp.power(cp.power(H,2) + cp.power(X,2),0.5) <= L,
    X.sum() == 4
    ]
print(constraints)

#Define Objective
objective = cp.Minimize(T)
prob = cp.Problem(objective, constraints)
prob.solve(solver=cp.MOSEK, verbose=True)

[Inequality(Expression(AFFINE, NONNEGATIVE, (3,))), Inequality(Expression(UNKNOWN, NONNEGATIVE, (3,))), Equality(Expression(AFFINE, NONNEGATIVE, ()), Constant(CONSTANT, NONNEGATIVE, ()))]
                                     CVXPY                                     
                                     v1.4.1                                    
(CVXPY) Oct 16 10:27:15 AM: Your problem has 7 variables, 3 constraints, and 0 parameters.
(CVXPY) Oct 16 10:27:15 AM: It is compliant with the following grammars: 
(CVXPY) Oct 16 10:27:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Oct 16 10:27:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Oct 16 10:27:15 AM: Your problem is compiled with the CPP canonicalization backend.


DCPError: Problem does not follow DCP rules. Specifically:
The following constraints are not DCP:
power(power([1.  1.  0.5], 2.0) + power(var298, 2.0), 0.5) <= var299 , because the following subexpressions are not:
|--  power(power([1.  1.  0.5], 2.0) + power(var298, 2.0), 0.5)

In [10]:
print(L.value)
print(X.value)
print(np.power(np.power(X.value,2) + np.power(H,2),0.5))

[3.16172362 2.10781574 2.43209509]
[1.47028012 1.05252826 1.47719162]
[1.77812362 1.45183186 1.55951758]
